### ISSUE TITLE
Publish on Clojars

### ISSUE THREAD

**Issue by jvandyke** [ohpauleez/lein-pedestal#1]
Hi @ohpauleez,

Is there anyway you can go ahead and publish this on Clojars? We're using this and would rather not pollute Clojars with own own version if we don't have to.

**Comment by ohpauleez** [comment]
It's there, it just doesn't appear in search for some reason:
https://clojars.org/ohpauleez/lein-pedestal

Also in the future (maybe today), I'm going to move some of this core code over to pedestal itself (to allow other tools to programmatically hook into it).

**Comment by jvandyke** [comment]
Ah, thanks! Your docs leave out the "ohpauleez/" part of the dependency.

Having it built into Pedestal would be awesome. Let me know if you need any
help testing.

James

**Comment by ohpauleez** [comment]
Whoa, thanks for pointing that out!
I'll definitely keep you posted when that change happens.  Thanks for using the plugin!  The code should spell out all of the options, but if you ever need help or want something changed, just open an issue.

Paul
