### ISSUE TITLE
uberwar-name option not working

### ISSUE THREAD

**Issue by jvandyke** [ohpauleez/lein-pedestal#2]
Looks like :pedestal :uberwar-name isn't respected.

My config:

``` clojure
;; In project.clj
:pedestal {:server-ns "my-project.server"
               :uberwar-name "my-project.war"}
```

Running `lein pedestal uberwar` outputs

```
Created /.../my-project/target/my-project-0.0.1-SNAPSHOT-standalone.war
```

Passing a name via the command line works. I'll try to figure it out and submit a PR.

**Comment by ohpauleez** [comment]
I Just saw your pull request - fixed on master.  Pushed new version to Clojars: 0.1.0-beta10

I like your README updates, I'll pull those in.
